name: Publish to Nuget

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish NuGet 2
        uses: Rebel028/publish-nuget@v2.8.0
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: BemIt/BemIt.csproj
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
